import { Schema, model } from "mongoose";
import slugify from "slugify";

/**
 * @typedef Product
 * @property {String} name                  - Name of the product (required, trimmed)
 * @property {String} description           - Description of the product (optional, trimmed)
 * @property {Number} price                 - Product price in local currency (required, min: 0)
 * @property {String[]} images              - Array of image URLs (max: 5)
 * @property {String} category              - Category label (required, lowercase, trimmed)
 * @property {Number} stock                 - Units in stock (required, min: 0)
 * @property {String} slug                  - URL-friendly unique identifier (auto-generated from name if not provided)
 * @property {Boolean} isPublished          - Visibility toggle for public listing (default: false)
 * @property {Schema.Types.ObjectId} createdBy - Reference to the User who created the product
 * @property {Date} createdAt               - Timestamp of creation (auto-generated by Mongoose)
 * @property {Date} updatedAt               - Timestamp of last update (auto-generated by Mongoose)
 *
 * @index {Object} { name: "text", description: "text", category: "text" } - Compound text index for full-text search
 */
const productSchema = new Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
      default: "",
    },
    description: {
      type: String,
      default: "",
      trim: true,
    },
    price: {
      type: Number,
      required: true,
      min: 0,
    },
    images: {
      type: [String],
      default: [],
      validate: {
        validator: function (array) {
          return array.length <= 5;
        },
        message: "Maximum of 5 images allowed",
      },
    },
    category: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
    },
    stock: {
      type: Number,
      required: true,
      min: 0,
    },
    slug: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    isPublished: {
      type: Boolean,
      default: false,
    },
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
    },
  },
  { timestamps: true }
);

// Auto-generate slug from product name
productSchema.pre("save", function (next) {
  if (!this.slug && this.name) {
    this.slug = slugify(this.name, {
      lower: true,
      strict: true,
      trim: true,
    });
  }
  next();
});

// Compound text index for keyword search
productSchema.index({
  name: "text",
  description: "text",
  category: "text",
});

const Product = model("Product", productSchema);
export default Product;
